### ISSUE TITLE
Add steps to get started in README.md

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [Snowflake-Labs/terraform-snowflake-aws-geff#25]

**Comment by sfc-gh-pkommini** [comment]
@sfc-gh-afedorov Does this not address the requirement here? https://github.com/Snowflake-Labs/terraform-snowflake-aws-geff/blob/main/README.md#setup-instructions

**Comment by sfc-gh-pkommini** [comment]
Let me know what other specific instructions you want added.

**Comment by sfc-gh-afedorov** [comment]
yes, iirc the "Setup Instructions" section was added since this and is great, ty

**Comment by sfc-gh-pkommini** [comment]
Oh I see. I thought this was new. 👍

**Comment by sfc-gh-pkommini** [comment]
Added more SQL specific instructions: https://github.com/Snowflake-Labs/terraform-snowflake-aws-geff
