### ISSUE TITLE
Unresolved references api_aws_external_id and api_aws_iam_user_arn

### ISSUE THREAD

**Issue by JimMcKenzieSmith** [Snowflake-Labs/terraform-snowflake-aws-geff#42]
https://github.com/Snowflake-Labs/terraform-snowflake-aws-geff/blob/9f990637b4788c63746b4ef5d166405f4a006c0a/iam.tf#L50-L55

Hello, when I have tried to use this repo, these two references (api_aws_external_id and api_aws_iam_user_arn on lines 50 and 55) show up as "unresolved" and throw errors with a `terraform plan`.  I've confirmed I am on the correct version of the provider. I've tried 0.25.23 which is what you have in this repo, and I've tried the latest version 0.25.25.  Both have the same issue.  I thought maybe this was a bug with the provider, but it seems that you've been able to get this to work?  Please confirm.

**Comment by JimMcKenzieSmith** [comment]
Actually, it looks like I was able to now get `terraform plan` to successfully run and this is more of an Intellij issue.

**Comment by sfc-gh-pkommini** [comment]
Glad to hear it was resolved. We do have github actions workflow that does the terraform validate so unresolved references should ideally be caught in hose checks.
